### ISSUE TITLE
Metadata/MetadataBuffer doesn't contain the latest values

### ISSUE THREAD

**Issue by Praveen2106** [googledrive/android-demos#20]
Hi,
Thanks for the demo. It is really helpful.
I'm facing an issue with, MetadataBuffer or metadata. It doesn't contain the latest values. For example, the metadata.getModifiedDate().getTime(); is having an older value, however the file contains the latest data. This becomes a problem when i try to resolve any conflict. Also, when i create a file on different device, it doesn't show here (Tried enabling Auto Sync, requestSync, clearing GPS cache, everything).

**Comment by Alchete** [comment]
I had the exact same issue, and finally solved it with a trick --

You need to OPEN the file first, before reading the metadata.  This appears to force the API to fetch the file from the cloud, rather than reading a local/cached copy.

    DriveFile file;

    // Trick Google Drive into fetching the remote file
    // which has the latest metadata
    file.open( getGoogleApiClient(), DriveFile.MODE_READ_ONLY, null).await();

    DriveResource.MetadataResult result = file.getMetadata(getGoogleApiClient()).await();
    Metadata metadata = result.getMetadata();

    // Get the modified date
    metadata.getModifiedDate();

See:  http://stackoverflow.com/questions/27872023/android-google-drivefile-metadata-is-cached-and-not-fetched-from-the-cloud

I'd like to know if this is intended behavior...because it really needs to be documented.

**Comment by kroikie** [comment]
[ChangeSubscriptions][1] may be a better option
[1]: https://developers.google.com/drive/android/events
