### ISSUE TITLE
issue on import com.google.android.gms.drive.events.DriveEvent.Listener;

### ISSUE THREAD

**Issue by dread1888** [googledrive/android-demos#24]
Hi,

I imported the project using android studio and when I compile it throw me an error that import com.google.android.gms.drive.events.DriveEvent.Listener; is not recognise

This is the only issue I encounter, if I remove the usage of the Listener, the project is working fine and can launch

My build gradle is like the below
dependencies {
    compile 'com.android.support:support-v4:21.0.2'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.android.support:appcompat-v7:21.0.2'
}

Try to google out, seem i the only one having the issue

**Comment by seanpjanson** [comment]
It is caused by play-services:6.5.87. I hope they will upgrade the code soon. Meanwhile, I've made these mods in my code:

  final private ChangeListener changeListener = new ChangeListener() {
    @Override
    public void onChange(ChangeEvent changeEvent) {
      mLogTextView.setText(String.format("File change event: %s", changeEvent));
    }
  };

**Comment by Winghin2517** [comment]
I have the exact same problem. It looks like the com.google.android.gms.drive.events.DriveEvent.Listener class doesn't exist anymore on Google's Android Developers site - are you sure it is caused by play-services:6.5.87?
If I go to the following site and expand the inherited methods or inherited constants, you will not see one called Listener.
https://developer.android.com/reference/com/google/android/gms/drive/events/DriveEvent.html

**Comment by seanpjanson** [comment]
As you see in the comment above yours, it is called "ChangeListener" now. See:
http://stackoverflow.com/questions/27887854/what-happened-to-listener-with-a-new-version-of-google-play-services
